version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck  # includes gosimple checks in v2
    - unused
  exclusions:
    presets:
      - std-error-handling  # ignore common errors like Close(), Write(), etc.
    rules:
      # Exclude test files from errcheck
      - path: _test\.go
        linters:
          - errcheck
  settings:
    errcheck:
      # Don't check for unchecked errors for common patterns
      exclude-functions:
        - (github.com/RevCBH/choo/internal/scheduler.Scheduler).Transition
        - (github.com/RevCBH/choo/internal/worker.Pool).Submit
        - (github.com/RevCBH/choo/internal/worker.Pool).Wait
        - (github.com/RevCBH/choo/internal/git.WorktreeManager).RemoveWorktree
        - (*encoding/json.Encoder).Encode
        - os.MkdirAll
    staticcheck:
      # Only enable SA checks (semantic analysis), not ST (style) or QF (quick fixes)
      checks:
        - "SA*"
        - "-SA1019"  # Allow deprecated symbols for now (grpc migration ongoing)
